kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: security-agent-demo
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
